//*****************************************************************************
// Author:      Chayton
// Date:        04/2015
// ProgramName: OgreSwamp
// Description: A map that solves a maze that can be inputted by the user or
//      a map can randomly be generated by the program.
//*****************************************************************************
package com.github.chaytonscott.OgreSwamp;

import java.util.Scanner;

public class OgreSwamp {
    Map map = new Map();
    final int MAX_DIMENSIONS = 10;
    public static void main(String [] args) {
        OgreSwamp controller = new OgreSwamp();
        controller.startSystem();
    }

    public void startSystem() {
        System.out.printf("Welcome to Ogre Swamp, please enter a map. (Type random to randomly generate a map)\n");
        String input[] = getInput();
        generateMap(input);
        printMap();
    }

    public String[] getInput() {
        Scanner in = new Scanner(System.in);
        String input[] = new String[MAX_DIMENSIONS];
        for (int i = 0; i < 10; i++) {
            input[i] = in.nextLine();
        }

        while(!validInput(input)) {
            System.out.print("Invalid input, please try again...\n");
            for (int i = 0; i < MAX_DIMENSIONS; i++) {
                input[i] = in.nextLine();
            }
        }
        return input;
    }

    public boolean validInput(String input[]) {
        if (input[0].equalsIgnoreCase("random")) {
            return true;
        }

        for (int i = 0; i < MAX_DIMENSIONS; i++) {
            if (input[i].charAt(i) == '@' || input[i].charAt(i) == '.' || input[i].charAt(i) == '$' || input[i].charAt(i) == 'O') {
            } else {
                return false;
            }
        }
        return true;
    }

    public void generateMap(String[] input) {
        int tempMap[][] = new int[MAX_DIMENSIONS][MAX_DIMENSIONS];
        for (int line = 0; line < 9; line++) {
            for (int column = 0; column < 10; column++) {
                if (input[line].charAt(column) == '.') {
                    tempMap[line][column] = 0;
                } else if (input[line].charAt(column) == 'O') {
                    tempMap[line][column] = 3;
                } else if (input[line].charAt(column) == '$') {
                    tempMap[line][column] = 6;
                } else if (input[line].charAt(column) == '@') {
                    tempMap[line][column] = 9;
                }
            }
        }
        map = new Map(tempMap);
    }









    //Method to print the map...
    public void printMap() {
        int[][] printMap = map.getMap();
        for (int x = 0; x < MAX_DIMENSIONS; x++) {
            for (int y = 0; y < MAX_DIMENSIONS; y++) {
                System.out.printf("%d", printMap[x][y]);
            }
            System.out.println();
        }
    }
}